FROM continuumio/miniconda3

LABEL maintainer="Matthew Tralka"

WORKDIR /PPCC

COPY environment2.yml .environment.yml
RUN conda env create -f environment.yml
RUN echo "source activate PPCC" > ~/.bashrc
ENV PATH /opt/conda/envs/PPCC/bin:$PATH
# RUN /bin/bash -c "source activate PPCC"

COPY . .

