FROM continuumio/miniconda3

LABEL maintainer="Matthew Tralka"

WORKDIR /PPCC

COPY environment.yml .
RUN CONDA_RESTORE_FREE_CHANNEL=1 conda env create -f environment.yml

SHELL ["conda", "run", "-n", "PPCC", "/bin/bash", "-c"]

COPY . .

ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "PPCC", "python", "main.py"]