FROM continuumio/miniconda3

LABEL maintainer="Matthew Tralka"

WORKDIR /PythonPhaseCrossCorrelation

COPY environment.yml .

RUN CONDA_RESTORE_FREE_CHANNEL=1 conda env create -f environment.yml

RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y \
    python-dev python3-dev \
    build-essential libxslt-dev \
    libffi-dev libssl-dev \
    python-setuptools

COPY . .

RUN cd PCC/CPU && \
    conda run --no-capture-output -n PPCC \
    python setup.py build_ext --inplace

CMD ["conda", "run", "--no-capture-output", "-n", \
    "PPCC", "jupyter", "notebook", "--allow-root", \
    "--no-browser", "--ip=0.0.0.0"]